import {organization} from "./oragnization.interface";

export let orgData:Array<organization> = [
    {
        orgID : '1303',
        orgName : 'macmacmac',
        parentOrg : 'stevejobs',
        upo : '123123',
        companyURL : 'apple.com',
        lastModified : '17-12-2005',
        status : 'Pending',
        loginName:'dfgh',
        password : 'sdfghj',
        confirmPassword:'sdfghj',
        street1 : 'sdfgh',
        street2 : 'sdfgh',
        city:'sdfgh',
        state:'sdfgh',
        zip:234567,
        county:'sdfgh',
        country : 'Algeria',
        group : 'sdfgh',
        category : 'Medical-Health',
        reportsTo : 'self',
        isAContractor :'yes',
        expDate:'4/5/16',
        role: 'sales',
        email: 'susa.sushma@gmail.com',
        team: 'Juan Tobias cpf',
        created: '04/08/05',
        title : 'ChanChanMan'
    },

    {
        orgID : '1301',
        orgName : 'macmacmac1',
        parentOrg : 'stevejobs',
        upo : '123123',
        companyURL : 'apple.com',
        lastModified : '17-12-2005',
        status : 'Active',
        loginName:'dfgh',
        password : 'sdfghj',
        confirmPassword:'sdfghj',
        street1 : 'sdfgh',
        street2 : 'sdfgh',
        city:'sdfgh',
        state:'sdfgh',
        zip:234567,
        county:'sdfgh',
        country : 'Algeria',
        group : 'sdfgh',
        category : 'Medical-Health',
        reportsTo : 'self',
        isAContractor :'yes',
        expDate:'4/5/16',
        role: 'sales',
        email: 'susa.sushma@gmail.com',
        team: 'Juan Tobias cpf',
        created: '04/08/05',
        title : 'ChanChanMan'
    },

    {
        orgID : '1304',
        orgName : 'macmacmac2',
        parentOrg : 'stevejobs',
        upo : '123123',
        companyURL : 'apple.com',
        lastModified : '17-12-2005',
        status : 'Cool',
        loginName:'dfgh',
        password : 'sdfghj',
        confirmPassword:'sdfghj',
        street1 : 'sdfgh',
        street2 : 'sdfgh',
        city:'sdfgh',
        state:'sdfgh',
        zip:234567,
        county:'sdfgh',
        country : 'Algeria',
        group : 'sdfgh',
        category : 'Medical-Health',
        reportsTo : 'self',
        isAContractor :'yes',
        expDate:'4/5/16',
        role: 'sales',
        email: 'susa.sushma@gmail.com',
        team: 'Juan Tobias cpf',
        created: '04/08/05',
        title : 'ChanChanMan'
    },
    {
        orgID : 'mac27',
        orgName : 'macmacmac4',
        parentOrg : 'stevejobs',
        upo : '123123',
        companyURL : 'apple.com',
        lastModified : '17-12-2005',
        status : 'Cool',
        loginName:'dfgh',
        password : 'sdfghj',
        confirmPassword:'sdfghj',
        street1 : 'sdfgh',
        street2 : 'sdfgh',
        city:'sdfgh',
        state:'sdfgh',
        zip:234567,
        county:'sdfgh',
        country : 'Algeria',
        group : 'sdfgh',
        category : 'Medical-Health',
        reportsTo : 'self',
        isAContractor :'yes',
        expDate:'4/5/16',
        role: 'sales',
        email: 'susa.sushma@gmail.com',
        team: 'Juan Tobias cpf',
        created: '04/08/05',
        title : 'ChanChanMan'
    }
];

