import {User} from "./users.interface";
export let UsersData:Array<User> = [
  {
    lastName: 'AMsadf',
    firstName:'AMsdf',
    onlineName: 'souravjaiswal',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'sourav',
    password : 'password',
    confirmPassword:'password',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'Algeria',
    group : 'sdfgh',
    category : 'Medical-Health',
    reportsTo : 'self',
    isAContractor :'yes',
    expDate:'4/5/16',
    role: 'sales',
    email: 'susa.sushma@gmail.com',
    team: 'Juan Tobias cpf',
    created: '04/08/05',
    status: 'Inactive'
  },
  {
    lastName: 'AbdelMessihxx',
    firstName: 'Adriaxx',
    onlineName: 'adriana',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'dfgh',
    password : 'sdfghj',
    confirmPassword:'sdfghj',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'sdfgh',
    group : 'sdfgh',
    category : 'sdfgh',
    reportsTo : 'sdfgh',
    isAContractor :'sdfgh',
    expDate:'4/5/16',
    role: 'admin',
    email: 'adrian.messi@gmail.com',
    team: 'KAM-West',
    created: '04/02/04',
    status: 'Active'
  },
  {
    lastName: 'Varela Lopes',
    firstName: 'Ana',
    onlineName: 'anav',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'dfgh',
    password : 'sdfghj',
    confirmPassword:'sdfghj',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'sdfgh',
    group : 'sdfgh',
    category : 'sdfgh',
    reportsTo : 'sdfgh',
    isAContractor :'sdfgh',
    expDate:'4/5/16',
    role: '',
    email: 'ana.varela@gmail.com',
    team: '',
    created: '06/02/04',
    status: 'Inactive'
  },
  {
    lastName: 'Osero',
    firstName: 'Andy',
    onlineName: 'andyo',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'dfgh',
    password : 'sdfghj',
    confirmPassword:'sdfghj',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'sdfgh',
    group : 'sdfgh',
    category : 'sdfgh',
    reportsTo : 'sdfgh',
    isAContractor :'sdfgh',
    expDate:'4/5/16',
    role: 'SR',
    email: 'o.andy@gmail.com',
    team: 'Juan Tobias cpf',
    created: '12/06/10',
    status: 'Active'
  },
  {
    lastName: 'Liu',
    firstName:'Anque',
    onlineName: 'angus',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'dfgh',
    password : 'sdfghj',
    confirmPassword:'sdfghj',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'sdfgh',
    group : 'sdfgh',
    category : 'sdfgh',
    reportsTo : 'sdfgh',
    isAContractor :'sdfgh',
    expDate:'4/5/16',
    role: 'AM Mgr',
    email: 'li.angus@gmail.com',
    team: 'Juan Tobias cpf',
    created: '12/06/10',
    status: 'Active'
  },
  {
    lastName: '',
    firstName:'sandra',
    onlineName: 'sandy',
    workPhone :4567,
    homePhone :34567,
    cellPhone :34567,
    loginName:'dfgh',
    password : 'sdfghj',
    confirmPassword:'sdfghj',
    street1 : 'sdfgh',
    street2 : 'sdfgh',
    city:'sdfgh',
    state:'sdfgh',
    zip:234567,
    county:'sdfgh',
    country : 'sdfgh',
    group : 'sdfgh',
    category : 'sdfgh',
    reportsTo : 'sdfgh',
    isAContractor :'sdfgh',
    expDate:'4/5/16',
    role: 'sales',
    email: 'susa.sushma@gmail.com',
    team: 'Juan Tobias cpf',
    created: '12/06/10',
    status: 'Active'
  }

  ];
