import {Team} from "./teams.interface";
export let TeamsData:Array<Team> = [
  {
    id: 210,
    name: '2312',
    lead: 'Tom Jerry',
    group: 'Finance',
    created: '12/06/10',
    status: 'Active',
    type : 'Business Unit',
    channel : 'Option 1',
    parentTeam : 'Sales',
    roles : 'Option 1',
    csmMapping : 'Option 1',
    area : 'Option 1',
    region : 'Option 1',
    country : 'India',
    territory : 'Option 1'
  },
  {
    id: 211,
    name: '2312',
    lead: 'Andrea Gheritti',
    group: 'Finance',
    created: '12/06/10',
    status: 'Active',
    type : 'Business Unit',
    channel : 'Channel 1',
    parentTeam : 'Option 1',
    roles : 'Option 1',
    csmMapping : 'Option 1',
    area : 'Option 1',
    region : 'Option 1',
    country : 'India',
    territory : 'Option 1'
  },
  {
    id: 212,
    name: '2312',
    lead: 'Andrea Gheritti',
    group: 'Finance',
    created: '12/06/10',
    status: 'Active',
    type : 'Business Unit',
    channel : 'Channel 1',
    parentTeam : 'Option 1',
    roles : 'Option 1',
    csmMapping : 'Option 1',
    area : 'Option 1',
    region : 'Option 1',
    country : 'India',
    territory : 'Option 1'
  },
  {
    id: 213,
    name: '2312',
    lead: 'Andrea Gheritti',
    group: 'Finance',
    created: '12/06/10',
    status: 'Active',
    type : 'Business Unit',
    channel : 'Channel 1',
    parentTeam : 'Option 1',
    roles : 'Option 1',
    csmMapping : 'Option 1',
    area : 'Option 1',
    region : 'Option 1',
    country : 'India',
    territory : 'Option 1'
  },
  {
    id: 214,
    name: '2312',
    lead: 'Andrea Gheritti',
    group: 'Finance',
    created: '12/06/10',
    status: 'Active',
    type: 'Business Unit',
    channel: 'Channel 1',
    parentTeam : 'Option 1',
    roles: 'Option 1',
    csmMapping: 'Option 1',
    area: 'Option 1',
    region: 'Option 1',
    country: 'India',
    territory: 'Option 1'
  }
];
